---
RSS:
    - http://www.blesk.cz/rss
    - http://servis.idnes.cz/rss.asp?c=zpravodaj
    - http://www.lidovky.cz/export/rss.asp
    - http://www.tyden.cz/rss-export.php
    - http://ihned.cz/?p=000000_rss
    - http://aktualne.centrum.cz/export/rss-hp.phtml
    - http://www.ceskenoviny.cz/sluzby/rss/index.php
    - http://www.financninoviny.cz/sluzby/rss/index.php
    - http://bleskove.aktualne.centrum.cz/export/rss-bleskove-hp.phtml
data_address: ../data
min_word_length: 3
max_theme_length: 10
counter_first_named: 30
counter_first_themes: 15
tagger_wanted_named:
    - g
    - m
    - q
    - P
    - ps